version: "3.9"

services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - db
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/ssl:/etc/nginx/ssl

  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: .docker/backend
      dockerfile: Dockerfile
    volumes:
      - ./${SOURCE_DIR_NAME}:/app
    ports:
      - ${APP_HOST_PORT}:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: ${PROJECT_NAME}_db
    platform: linux/x86_64
    build: 
      context: .docker/db
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build: 
      context: .docker/frontend
    volumes:
      - ./${SOURCE_DIR_NAME_FRONT}:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - ${FRONT_HOST_PORT}:3000
    stdin_open: true

  minio:
    container_name: ${PROJECT_NAME}_minio
    image: minio/minio
    ports:
      - ${MINIO_HOST_PORT1}:9999
      - ${MINIO_HOST_PORT2}:9001
    volumes:
      - ./.docker/minio/data:/export
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
      MINIO_DEFAULT_BUCKETS: uploads:public
    command: server /export --address :9999 --console-address :9001

  create-bucket:
    image: minio/mc
    entrypoint: [ "" ]
    command:
      - /bin/sh
      - -c
      - |
        server /data --console-address :9001
        until (mc config host add minio http://minio:9999 access_key secret_key) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/uploads
        mc anonymous set public minio/uploads
    depends_on:
      - minio