version: "3.9"

services:
  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: .docker/backend
      dockerfile: Dockerfile
    volumes:
      - ./${SOURCE_DIR_NAME}:/app
    ports:
      - ${APP_HOST_PORT}:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: ${PROJECT_NAME}_db
    platform: linux/x86_64
    build: 
      context: .docker/db
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build: 
      context: .docker/frontend
    volumes:
      - ./${SOURCE_DIR_NAME_FRONT}:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - ${FRONT_HOST_PORT}:3000
    stdin_open: true