version: "3.9"

services:
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: .docker/app
      dockerfile: Dockerfile
    volumes:
      - ./${SOURCE_DIR_NAME}:/app
    ports:
      - ${APP_HOST_PORT}:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: ${PROJECT_NAME}_db
    platform: linux/x86_64
    build: 
      context: .docker/db
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo