export const ARTICLE_ENDPOINT = '/v1/articles'
export const TAG_ENDPOINT = '/v1/tags'
export const UPLOAD_ENDPOINT = '/v1/uploads'
export const UPLOAD_THUMBNAIL_ENDPOINT = '/v1/uploads/thumbnail'
export const LOGIN_ENDPOINT = '/v1/users/login'
export const ME_ENDPOINT = '/v1/users/me'
export const USERS_ENDPOINT = '/v1/users'
