"""create aggregate_access_logs table

Revision ID: 3092814652b2
Revises: 886fcf475209
Create Date: 2023-11-25 09:47:31.877059+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3092814652b2'
down_revision: Union[str, None] = '886fcf475209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregate_access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visit_url', sa.String(length=128), nullable=False, comment='アクセスしたページのURL'),
    sa.Column('article_id', sa.BigInteger(), nullable=True, comment='記事ID'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='アクセス数'),
    sa.Column('target_year', sa.Integer(), nullable=True, comment='対象年'),
    sa.Column('target_month', sa.Integer(), nullable=True, comment='対象月'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('target_year', 'target_month', 'visit_url', name='uq_target_year_month_url'),
    sa.PrimaryKeyConstraint('id'),
    comment='月毎・ページ毎のアクセス数の合計を管理するテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregate_access_logs')
    # ### end Alembic commands ###
