"""create tokens table

Revision ID: da1f73ca3229
Revises: c9da252697cc
Create Date: 2023-10-28 15:23:01.325379+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1f73ca3229'
down_revision: Union[str, None] = 'c9da252697cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False, comment='アクセストークン'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ユーザーID'),
    sa.Column('expired_at', sa.DateTime(), nullable=False, comment='トークンの有効期限'),
    sa.Column('last_login_at', sa.DateTime(), nullable=False, comment='最終ログイン日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='トークンテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
