"""create articles table

Revision ID: dfc777810a72
Revises: da1f73ca3229
Create Date: 2023-10-28 15:23:43.101436+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc777810a72'
down_revision: Union[str, None] = 'da1f73ca3229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='記事タイトル'),
    sa.Column('content', sa.Text(), nullable=False, comment='記事内容'),
    sa.Column('target_year', sa.Integer(), nullable=True, comment='対象年'),
    sa.Column('target_month', sa.Integer(), nullable=True, comment='対象月'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='投稿済みかどうか'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='記事テーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
