"""create users table

Revision ID: 404becc2b6d9
Revises: 00f3fcb8899d
Create Date: 2023-10-20 04:02:58.048429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404becc2b6d9'
down_revision = '00f3fcb8899d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='ユーザー名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='パスワード'),
    sa.Column('role', sa.Integer(), nullable=True, comment='ロール. 0:admin, 1:member'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='usersテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
