"""create tokens table

Revision ID: c26a86cf7031
Revises: 404becc2b6d9
Create Date: 2023-10-20 04:04:44.417918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26a86cf7031'
down_revision = '404becc2b6d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False, comment='アクセストークン'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ユーザーID'),
    sa.Column('expired_at', sa.DateTime(), nullable=False, comment='トークンの有効期限'),
    sa.Column('last_login_at', sa.DateTime(), nullable=False, comment='最終ログイン日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='トークンテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
